int strcmp(char* src,char* obj,int len);
void printSentence(char* str,int a,int b,int len,int style);
void ClearScreen(int x_top,int y_top,int x_down,int y_down);
char Listen_Keyboard();
void Task(char* userinput);
void Shutdown();
void Load(void* addr,int beg,int num);
void Showtable();
void RunProg(void* addr);
int run_resolve(char* src);